// This source code file is AUTO-GENERATED by github.com/taskcluster/jsonschema2go

package helloengine

import "github.com/taskcluster/taskcluster-worker/runtime"

type (
	payload struct {
		Name string `json:"name"`
	}
)

var payloadSchema = func() runtime.CompositeSchema {
	schema, err := runtime.NewCompositeSchema(
		"start",
		`
		{
		  "$schema": "http://json-schema.org/draft-04/schema#",
		  "additionalProperties": false,
		  "properties": {
		    "name": {
		      "type": "string"
		    }
		  },
		  "required": [
		    "name"
		  ],
		  "title": "Payload",
		  "type": "object"
		}
		`,
		true,
		func() interface{} {
			return &payload{}
		},
	)
	if err != nil {
		panic(err)
	}
	return schema
}()
